//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.BigDataTest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Camera.
    /// </summary>
    // *** Start programmer edit section *** (Camera CustomAttributes)

    // *** End programmer edit section *** (Camera CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Camera : ICSSoft.STORMNET.DataObject
    {
        
        private int fCameraId;
        
        private int fGroupId;
        
        private int fGroupName;
        
        private bool fActual;
        
        private System.DateTime fCreateTime;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fEditTime;
        
        private NewPlatform.BigDataTest.RegObject fRegObject;
        
        // *** Start programmer edit section *** (Camera CustomMembers)

        // *** End programmer edit section *** (Camera CustomMembers)

        
        /// <summary>
        /// CameraId.
        /// </summary>
        // *** Start programmer edit section *** (Camera.CameraId CustomAttributes)

        // *** End programmer edit section *** (Camera.CameraId CustomAttributes)
        public virtual int CameraId
        {
            get
            {
                // *** Start programmer edit section *** (Camera.CameraId Get start)

                // *** End programmer edit section *** (Camera.CameraId Get start)
                int result = this.fCameraId;
                // *** Start programmer edit section *** (Camera.CameraId Get end)

                // *** End programmer edit section *** (Camera.CameraId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.CameraId Set start)

                // *** End programmer edit section *** (Camera.CameraId Set start)
                this.fCameraId = value;
                // *** Start programmer edit section *** (Camera.CameraId Set end)

                // *** End programmer edit section *** (Camera.CameraId Set end)
            }
        }
        
        /// <summary>
        /// GroupId.
        /// </summary>
        // *** Start programmer edit section *** (Camera.GroupId CustomAttributes)

        // *** End programmer edit section *** (Camera.GroupId CustomAttributes)
        public virtual int GroupId
        {
            get
            {
                // *** Start programmer edit section *** (Camera.GroupId Get start)

                // *** End programmer edit section *** (Camera.GroupId Get start)
                int result = this.fGroupId;
                // *** Start programmer edit section *** (Camera.GroupId Get end)

                // *** End programmer edit section *** (Camera.GroupId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.GroupId Set start)

                // *** End programmer edit section *** (Camera.GroupId Set start)
                this.fGroupId = value;
                // *** Start programmer edit section *** (Camera.GroupId Set end)

                // *** End programmer edit section *** (Camera.GroupId Set end)
            }
        }
        
        /// <summary>
        /// GroupName.
        /// </summary>
        // *** Start programmer edit section *** (Camera.GroupName CustomAttributes)

        // *** End programmer edit section *** (Camera.GroupName CustomAttributes)
        public virtual int GroupName
        {
            get
            {
                // *** Start programmer edit section *** (Camera.GroupName Get start)

                // *** End programmer edit section *** (Camera.GroupName Get start)
                int result = this.fGroupName;
                // *** Start programmer edit section *** (Camera.GroupName Get end)

                // *** End programmer edit section *** (Camera.GroupName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.GroupName Set start)

                // *** End programmer edit section *** (Camera.GroupName Set start)
                this.fGroupName = value;
                // *** Start programmer edit section *** (Camera.GroupName Set end)

                // *** End programmer edit section *** (Camera.GroupName Set end)
            }
        }
        
        /// <summary>
        /// Actual.
        /// </summary>
        // *** Start programmer edit section *** (Camera.Actual CustomAttributes)

        // *** End programmer edit section *** (Camera.Actual CustomAttributes)
        public virtual bool Actual
        {
            get
            {
                // *** Start programmer edit section *** (Camera.Actual Get start)

                // *** End programmer edit section *** (Camera.Actual Get start)
                bool result = this.fActual;
                // *** Start programmer edit section *** (Camera.Actual Get end)

                // *** End programmer edit section *** (Camera.Actual Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.Actual Set start)

                // *** End programmer edit section *** (Camera.Actual Set start)
                this.fActual = value;
                // *** Start programmer edit section *** (Camera.Actual Set end)

                // *** End programmer edit section *** (Camera.Actual Set end)
            }
        }
        
        /// <summary>
        /// CreateTime.
        /// </summary>
        // *** Start programmer edit section *** (Camera.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Camera.CreateTime CustomAttributes)
        public virtual System.DateTime CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Camera.CreateTime Get start)

                // *** End programmer edit section *** (Camera.CreateTime Get start)
                System.DateTime result = this.fCreateTime;
                // *** Start programmer edit section *** (Camera.CreateTime Get end)

                // *** End programmer edit section *** (Camera.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.CreateTime Set start)

                // *** End programmer edit section *** (Camera.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Camera.CreateTime Set end)

                // *** End programmer edit section *** (Camera.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// EditTime.
        /// </summary>
        // *** Start programmer edit section *** (Camera.EditTime CustomAttributes)

        // *** End programmer edit section *** (Camera.EditTime CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Camera.EditTime Get start)

                // *** End programmer edit section *** (Camera.EditTime Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fEditTime;
                // *** Start programmer edit section *** (Camera.EditTime Get end)

                // *** End programmer edit section *** (Camera.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.EditTime Set start)

                // *** End programmer edit section *** (Camera.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Camera.EditTime Set end)

                // *** End programmer edit section *** (Camera.EditTime Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.BigDataTest.RegObject.
        /// </summary>
        // *** Start programmer edit section *** (Camera.RegObject CustomAttributes)

        // *** End programmer edit section *** (Camera.RegObject CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ObjectId"})]
        public virtual NewPlatform.BigDataTest.RegObject RegObject
        {
            get
            {
                // *** Start programmer edit section *** (Camera.RegObject Get start)

                // *** End programmer edit section *** (Camera.RegObject Get start)
                NewPlatform.BigDataTest.RegObject result = this.fRegObject;
                // *** Start programmer edit section *** (Camera.RegObject Get end)

                // *** End programmer edit section *** (Camera.RegObject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Camera.RegObject Set start)

                // *** End programmer edit section *** (Camera.RegObject Set start)
                this.fRegObject = value;
                // *** Start programmer edit section *** (Camera.RegObject Set end)

                // *** End programmer edit section *** (Camera.RegObject Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of Camera.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfCamera CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfCamera CustomAttributes)
    public class DetailArrayOfCamera : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.BigDataTest.DetailArrayOfCamera members)

        // *** End programmer edit section *** (NewPlatform.BigDataTest.DetailArrayOfCamera members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Camera by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Camera.
        /// </summary>
        public DetailArrayOfCamera(NewPlatform.BigDataTest.RegObject fRegObject) : 
                base(typeof(Camera), ((ICSSoft.STORMNET.DataObject)(fRegObject)))
        {
        }
        
        public NewPlatform.BigDataTest.Camera this[int index]
        {
            get
            {
                return ((NewPlatform.BigDataTest.Camera)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.BigDataTest.Camera dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
